version: '3.4'

services:
  postgres:
    image: 'ankane/pgvector:v0.5.0'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '${PG_HOST_PORT:-5433}:5432'

volumes:
  postgres: